apiVersion: v1
kind: Pod
metadata:
  name: nfs
spec:
  containers:
  - name: nfs
    image: nginx:alpine
    volumeMounts:
    - name: persistent-storage
      mountPath: /opt
  volumes:
  - name: persistent-storage
    nfs:
      server: fs-6f79f3a4.efs.eu-west-1.amazonaws.com
      path: /
